### ISSUE TITLE
Cannot test HTTP functions that implement ExpressJS

### ISSUE THREAD

**Issue by ynigoreyes** [firebase/firebase-functions-test#29]
**firebase-functions-test:** 0.1.3

**firebase-functions:** 2.0.5

**firebase-admin:** 6.0.0

**express:** 4.16.3

### Test case
```javascript
// environment.js
const express = require('express')
const app = express()

app.get('/', (req, res) => {
    res.end()
})
```

```javascript
// index.js
module.exports.environment = functions.https.onRequest(require('./environment.js')
```

```javascript
// index.spec.js
require('firebase-functions-test')()
const { expect } = require('chai')
const functions = require('./index.js')

describe('TypeError', () => {
    it('Error: steam.listener is not a function', () => {
        res = { end: () => expect(true).to.equal(true) }
        req = { }
        functions.environment(req, res)
    })
})
```

### Steps to reproduce
I ran this kind of test case

### Expected behavior
To not error out

### Actual behavior
```
    TypeError: stream.listeners is not a function

      31 |     }
      32 |
    > 33 |     functions.environment(req, res)
         |               ^
      34 |   })
      35 | })
      36 |

      at hasPipeDataListeners (node_modules/unpipe/index.js:22:26)
      at unpipe (node_modules/unpipe/index.js:52:8)
      at send (node_modules/finalhandler/index.js:306:3)
      at node_modules/finalhandler/index.js:133:5
      at node_modules/express/lib/router/index.js:635:15
      at next (node_modules/express/lib/router/index.js:210:14)
      at Function.handle (node_modules/express/lib/router/index.js:174:3)
      at Function.handle (node_modules/express/lib/application.js:174:10)
      at app (node_modules/express/lib/express.js:39:9)
      at Object.cloudFunction [as environment] (node_modules/firebase-functions/lib/providers/https.js:57:9)
      at Object.environment (src/environment/environment.spec.js:33:15)
```

**Comment by thechenky** [comment]
@ynigoreyes thank you for your feedback. I'm a bit confused with what you're trying to do here. Can you provide more context? I also noticed some inconsistencies - `TypeError: stream.listeners is not a function` does not fully match the code in `index.spec.js` that you provided. Are you able to paste more of the `index.spec.js` file? The error points to line 33, but the provided snippet does not map to that.

**Comment by buzzware** [comment]
I solved this : https://stackoverflow.com/a/54019051/1682615
