### ISSUE TITLE
makeDataSnapshot signature not accepting null values

### ISSUE THREAD

**Issue by tjokimie** [firebase/firebase-functions-test#48]
`firebase-functions-test` `makeDataSnapshot` signature is not accepting `null` values.

This makes it impossible to test code using `change.after.exists()` without using `@ts-ignore`, for example:

```ts
const foo = functions.database.ref('/foo').onWrite(async (change, context) => {
  if (!change.after.exists()) {
    // skip
    return
  }
  // actual logic
})
```

In test you would want to use the following code but it throws `src/responses/__tests__/index.test.ts:143:54 - error TS2345: Argument of type 'null' is not assignable to parameter of type 'string | number | boolean | object | any[]'.`

```ts
const afterSnap = test.database.makeDataSnapshot(null, 'foo')
const change = test.makeChange(null, afterSnap)
```

`firebase-functions` `DataSnapshot` constructor still accepts `null` values as it has `any` type.

## Related signatures:

`makeDataSnapshot` signature: https://github.com/firebase/firebase-functions-test/blob/8ef3a117d19fc0729e151348733a63fab0bbe05d/src/providers/database.ts#L31

`DataSnapshot` constructor in `firebase-functions`: https://github.com/firebase/firebase-functions/blob/cc663231245256c444e54211911c25fbda0db3d3/src/providers/database.ts#L336

## Proposed fix:

The `makeDataSnapshot` signature should be changed either so that it would also allow `null` values or unify it with `DataSnapshot` constructor by allowing `any` values.

**Comment by laurenzlong** [comment]
Implemented in https://github.com/firebase/firebase-functions-test/pull/53

**Comment by rfitz123** [comment]
I'm also having an issue with makeDataSnapshot, used like so:
```
const snapshot = test.firestore.makeDocumentSnapshot({owner: 'testUserA', text: 'response from test user a'}, 'users/testUserA/questions/testQuestion/responses/testResponse');
```

That line gives me the error
```
(node:28967) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at App.getApp (/Users/riley/Work/Agape/agape-staging-api/functions/node_modules/firebase-functions-test/lib/app.js:40:65)
    at Object.makeDocumentSnapshot (/Users/riley/Work/Agape/agape-staging-api/functions/node_modules/firebase-functions-test/lib/providers/firestore.js:44:71)
    at Context.<anonymous> (/Users/riley/Work/Agape/agape-staging-api/functions/test/notification.test.js:100:37)
    at callFnAsync (/Users/riley/Work/Agape/agape-staging-api/functions/node_modules/mocha/lib/runnable.js:423:21)
    at Test.Runnable.run (/Users/riley/Work/Agape/agape-staging-api/functions/node_modules/mocha/lib/runnable.js:363:7)
    at Runner.runTest (/Users/riley/Work/Agape/agape-staging-api/functions/node_modules/mocha/lib/runner.js:546:10)
    at /Users/riley/Work/Agape/agape-staging-api/functions/node_modules/mocha/lib/runner.js:672:12
    at next (/Users/riley/Work/Agape/agape-staging-api/functions/node_modules/mocha/lib/runner.js:455:14)
    at /Users/riley/Work/Agape/agape-staging-api/functions/node_modules/mocha/lib/runner.js:465:7
    at next (/Users/riley/Work/Agape/agape-staging-api/functions/node_modules/mocha/lib/runner.js:367:14)
    at Immediate.<anonymous> (/Users/riley/Work/Agape/agape-staging-api/functions/node_modules/mocha/lib/runner.js:433:5)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
```

It seems to follow the documentation [here](https://firebase.google.com/docs/functions/unit-testing#using_custom_data).

firebase-functions version is 3.3.0
firebase-functions-test version is 0.1.7

**Comment by vractal** [comment]
Did you ever find out what it was @rfitz123 ?

**Comment by vractal** [comment]
It seems that something is cleaning up the env vars in the wrong time, specifically FIREBASE_CONFIG, which is used in `/node_modules/firebase-functions-test/lib/app.js`..
If I run my troubled test by itself, everything goes well, but when I run all tests, I get same error as @rfitz123  above. 
If I comment out all `test.cleanup()` in my code, then I can run all tests without a problem.

**Comment by vractal** [comment]
Should I open a new issue for this? Doesnt seem really related to the initial issue @laurenzlong

**Comment by inlined** [comment]
Yes, if you are still encountering this issue, please open another bug. The issue you are (were?) facing has nothing to do with supporting null values.
