### ISSUE TITLE
Custom claims can't be set on a user made with makeUserRecord

### ISSUE THREAD

**Issue by markgoho** [firebase/firebase-functions-test#89]
### Version info

**firebase-functions-test:** 0.2.3

**firebase-functions:** 3.13.1

**firebase-admin:** 9.4.2

### Test case

Create user with `makeUserRecord` and use that user in a test where custom claims are set.

#### custom claims function
``` typescript
const setCustomClaims = async (user: admin.auth.UserRecord) => {
  const isAdmin = admins.includes(user.email!);
  try {
    functions.logger.info('Setting custom claims for', user.displayName);
    await admin.auth().setCustomUserClaims(user.uid, {
      admin: isAdmin,
    });
  } catch (e) {
    functions.logger.error('Not able to assign custom claims', e);
  }
};
```

#### unit test
``` javascript
it('tests a firestore write', async () => {
  const wrapped = test.wrap(myFunctions.createUserRecord);
  const user = test.auth.makeUserRecord({
    uid: 'abc1234',
    email: 'markgoho@gmail.com',
    displayName: 'Mark Goho',
    photoURL: 'https://example.com',
  });

  await wrapped(user);

  const snap = await admin.firestore().doc('users/abc1234').get();
  expect(snap.data()).to.eql({
    admin: false,
    email: 'markgoho@gmail.com',
    displayName: 'Mark Goho',
    photoUrl: 'https://example.com',
  });
});
```

### Expected behavior

Custom claims can be set on test user.

### Actual behavior
from the `catch(e)` block above
``` bash
{"severity":"ERROR","message":"Not able to assign custom claims FirebaseAuthError: There is no user record corresponding to the provided identifier.
    at FirebaseAuthError.FirebaseError [as constructor] (C:\\Users\\Mark\\Documents\\IdeaCrew\\active-branch-tracker\\functions\\node_modules\\firebase-admin\\lib\\utils\\error.js:44:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (C:\\Users\\Mark\\Documents\\IdeaCrew\\active-branch-tracker\\functions\\node_modules\\firebase-admin\\lib\\utils\\error.js:90:28)
    at new FirebaseAuthError (C:\\Users\\Mark\\Documents\\IdeaCrew\\active-branch-tracker\\functions\\node_modules\\firebase-admin\\lib\\utils\\error.js:149:16)
    at Function.FirebaseAuthError.fromServerError (C:\\Users\\Mark\\Documents\\IdeaCrew\\active-branch-tracker\\functions\\node_modules\\firebase-admin\\lib\\utils\\error.js:188:16)
    at C:\\Users\\Mark\\Documents\\IdeaCrew\\active-branch-tracker\\functions\\node_modules\\firebase-admin\\lib\\auth\\auth-api-request.js:1526:49
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async setCustomClaims (C:\\Users\\Mark\\Documents\\IdeaCrew\\active-branch-tracker\\functions\\lib\\new-user\\new-user.js:19:9)
    at async Object.createNewUser (C:\\Users\\Mark\\Documents\\IdeaCrew\\active-branch-tracker\\functions\\lib\\new-user\\new-user.js:9:5)
    at async Function.run (C:\\Users\\Mark\\Documents\\IdeaCrew\\active-branch-tracker\\functions\\lib\\index.js:92:5)
    at async Context.<anonymous> (C:\\Users\\Mark\\Documents\\IdeaCrew\\active-branch-tracker\\functions\\test\\functions.spec.js:50:5) {
  errorInfo: {
    code: 'auth/user-not-found',
    message: 'There is no user record corresponding to the provided identifier.'
  },
  codePrefix: 'auth'
}"}

**Comment by samtstern** [comment]
@markgoho this feels like it's going to be an emulators issue somehow so let me move this over to `firebase-tools`
